apiVersion: batch/v1
kind: Job
metadata:
  name: room-service-database-initialiser-job
  namespace: peerprep
spec:
  template:
    metadata:
      namespace: peerprep
      labels:
        app: room-service-database-initialiser
    spec:
      containers:
        - name: room-service-database-initialiser
          image: ghcr.io/cs3219-ay2324s1-g04/peerprep_room_service_database_initialiser
          env:
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: room-service-database-client-config-map
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: room-service-database-client-secret
                  key: database-password
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: room-service-database-client-config-map
                  key: database-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: room-service-database-client-config-map
                  key: database-port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: room-service-database-client-config-map
                  key: database-name
            - name: DATABASE_CONNECTION_TIMEOUT_MILLIS
              valueFrom:
                configMapKeyRef:
                  name: room-service-database-client-config-map
                  key: database-connection-timeout-millis
            - name: DATABASE_MAX_CLIENT_COUNT
              valueFrom:
                configMapKeyRef:
                  name: room-service-database-client-config-map
                  key: database-max-client-count
            - name: SHOULD_FORCE_INITIALISATION
              value: 'false'
      restartPolicy: OnFailure
  backoffLimit: 10
