services:
  room_service_database:
    image: postgres:16-bookworm
    networks:
      - peerprep_network
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped

  room_service_mq:
    image: rabbitmq:3.12
    networks:
      - peerprep_network
    ports:
      - ${MQ_EXPOSED_PORT}:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
    restart: unless-stopped

  room_service_database_initialiser:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_room_service_database_initialiser:demo
    build:
      context: .
      dockerfile: ./dockerfiles/database_initialiser.dockerfile
    networks:
      - peerprep_network
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: room_service_database
      DATABASE_PORT: 5432
      DATABASE_SHOULD_USE_TLS: false
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT_MILLIS: ${DATABASE_CONNECTION_TIMEOUT_MILLIS}
      DATABASE_MAX_CLIENT_COUNT: ${DATABASE_MAX_CLIENT_COUNT}
      SHOULD_FORCE_INITIALISATION: ${SHOULD_FORCE_INITIALISATION}
    depends_on:
      - room_service_database
    restart: on-failure

  room_service_expired_room_deleter:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_room_service_expired_room_deleter:demo
    build:
      context: .
      dockerfile: ./dockerfiles/expired_room_deleter.dockerfile
    networks:
      - peerprep_network
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: room_service_database
      DATABASE_PORT: 5432
      DATABASE_SHOULD_USE_TLS: false
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT_MILLIS: ${DATABASE_CONNECTION_TIMEOUT_MILLIS}
      DATABASE_MAX_CLIENT_COUNT: ${DATABASE_MAX_CLIENT_COUNT}
      MQ_USER: ${MQ_USER}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_HOST: room_service_mq
      MQ_PORT: 5672
      MQ_VHOST: ''
      MQ_SHOULD_USE_TLS: false
      MQ_EXCHANGE_NAME: ${MQ_EXCHANGE_NAME}
      ROOM_DELETION_INTERVAL_MILLIS: ${ROOM_DELETION_INTERVAL_MILLIS}
    depends_on:
      - room_service_database
      - room_service_mq
    restart: unless-stopped

  room_service_api:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_room_service_api:demo
    build:
      context: .
      dockerfile: ./dockerfiles/api.dockerfile
    networks:
      - peerprep_network
    ports:
      - ${API_EXPOSED_PORT}:9003
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: room_service_database
      DATABASE_PORT: 5432
      DATABASE_SHOULD_USE_TLS: false
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT_MILLIS: ${DATABASE_CONNECTION_TIMEOUT_MILLIS}
      DATABASE_MAX_CLIENT_COUNT: ${DATABASE_MAX_CLIENT_COUNT}
      MQ_USER: ${MQ_USER}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_HOST: room_service_mq
      MQ_PORT: 5672
      MQ_VHOST: ''
      MQ_SHOULD_USE_TLS: false
      MQ_EXCHANGE_NAME: ${MQ_EXCHANGE_NAME}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      ROOM_EXPIRE_MILLIS: ${ROOM_EXPIRE_MILLIS}
      PORT: 9003
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - room_service_database
      - room_service_mq
    restart: unless-stopped

networks:
  peerprep_network:
    name: peerprep
    external: true
