apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: room-service-mq-client-secret
  namespace: peerprep
spec:
  encryptedData:
    mq-password: AgAE39KRnSH8Y1OvKi2xBT4xinR7/0lCmXEWKEe8fwH0qX1wQoi8lAfG0/HLcLS/uMYDaVujXtZ8SA+WjTJs0slLG1BZxaJ7RbJf5thtK15sDSMLu7zptwOqxHZLNCinl6UTfEaom9yXqZ4k7kf/jd61D5NsnTJR2V2TnyT1y+nTg2dy7HHLjBHtGWZr18cxh9OJOQA1y2NDHB+omTAmIoWoiaiwqfaiVZ5keWaBHFbglNjdlz8IAMs861nP4x5F8S0A55VdmLoh03GGU1mgHr43P2rPEpkewbeKMAfxjk4l6oi5CiCghcAT3OJrbi/nwaYThDYTFkSnAzqgcSanomq0HyeZXlQzTLLh31FOwr5Zl3SD5C8vfAWpH24UkLaPQm3iVxBeQtk57dXlzOCLWbyJnvdaeZR/F6D1XsiIVXZelZNULxCnJYV/iXgQHICEdjajUC4xe3CnQjRiD4JluI1XjIBAdhTJKv9+pnYbPEiEGTa6tu1uqrOoHxtP6RKXJn9WttPCj/WBWfZDJ9ylTspCc7hsTqT2Q81BxhVIfVP88FDEV4w3F4OuEWXuhRFlntm2hbSZiLTF61gZzS6/fWUiH75/IiJa+ef8DOSMubScgEO3kZqJl6PoNKY/O+F/EAiASdr14hhXtAKTvoQ6KkWRbc/RTsJ5GkBEMJG1toZOHm1x9x2ZggdQgYNU1AxvrkWgvsDtu8Z5mhTGmzlZqg39s5YktXSygaxBYLuJAJBQGQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: room-service-mq-client-secret
      namespace: peerprep
    type: Opaque

