apiVersion: v1
kind: Service
metadata:
  name: room-service-api-service
  namespace: peerprep
spec:
  selector:
    app: room-service-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
